name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Get package.json version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Set GIT env vars
        uses: FranzDiebold/github-env-vars-action@v2
      - name: Creating archive name
        run: echo "VERSION_ID=$(echo ${{ steps.package-version.outputs.current-version }}-$CI_RUN_NUMBER-$CI_SHA_SHORT)" >> $GITHUB_ENV
      - name: Displaying archive name
        run: echo ${{ env.VERSION_ID }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Creating artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-list-${{ env.VERSION_ID }}
          path: 'prod'
